# Generated by Django 4.2.13 on 2025-08-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lesson_quiz_submission_content_studentsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='sent_at',
        ),
    ]
