# Generated by Django 4.2.13 on 2025-08-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_module_created_by_alter_quiz_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_contents', to='app.lessoncontent'),
        ),
        migrations.AddField(
            model_name='module',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_modules', to='app.lesson'),
        ),
    ]
