# Generated by Django 4.2.13 on 2025-09-02 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_lesson_lesson_content_remove_module_lesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assessment', 'student')},
        ),
    ]
