# Generated by Django 4.2.13 on 2025-09-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_submission_options_studentsubmission_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
    ]
