# Generated by Django 4.2.13 on 2025-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_assessment_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
