# Generated by Django 4.2.13 on 2025-09-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sponsorship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='app.sponsor'),
        ),
    ]
